export const ApiPaths = {
  campaign: (identifier: string) => `/api/campaigns/${identifier}`,
  campaignManage: (identifier: string) => `/api/campaigns/${identifier}/manage`,
  campaignImage: (identifier: string) => `/api/campaigns/${identifier}/image`,
  campaignPublish: (identifier: string) => `/api/campaigns/${identifier}/publish`,
  campaigns: '/api/campaigns',
  ownedCampaigns: '/api/campaigns/mine',
  preorder: (identifier: string) => `/api/campaigns/${identifier}/preorders`,
  orderHistory: '/api/orders/me',
  orderPayment: (orderId: string) => `/api/orders/${orderId}/payment`,
  dashboard: '/api/dashboard',
  dashboardOverview: (campaignId: string) => `/api/dashboard/${campaignId}/overview`,
  milestone: (milestoneId: string) => `/api/production/milestones/${milestoneId}`,
  campaignMilestone: (campaignId: string) => `/api/campaigns/${campaignId}/milestones`,
  expense: (costItemId: string) => `/api/production/expenses/${costItemId}`,
  campaignExpense: (campaignId: string) => `/api/campaigns/${campaignId}/expenses`,
  profile: '/api/profile',
  profileImage: '/api/profile/image',
  profileBanner: '/api/profile/banner',
  artisanOnboarding: '/api/profile/artisan-onboarding',
} as const
